"""add payment recovery tables

Revision ID: 95f7c2bb04cb
Revises: 120e07d931a3
Create Date: 2026-08-26 07:33:47.923163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f7c2bb04cb'
down_revision: Union[str, None] = '120e07d931a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_contact', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_description', sa.String(length=512), nullable=True),
    sa.Column('failure_category', sa.String(length=32), nullable=True),
    sa.Column('retried_from_payment_id', sa.Integer(), nullable=True),
    sa.Column('razorpay_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['retried_from_payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_order_id', 'payments', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('failure_category', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_strategy', sa.String(length=32), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_cases_payment_id', 'recovery_cases', ['payment_id'], unique=False)
    op.create_index('ix_recovery_cases_status', 'recovery_cases', ['status'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)

    # Enforce "at most one non-terminal recovery case per payment" at the
    # database level -- the application-level check in
    # recovery_service.on_payment_failed() is the primary defense, but a
    # DB constraint is what actually protects against two concurrent
    # webhook deliveries both passing that check before either commits
    # (the same pattern Phase 1 uses for WebhookEvent's UniqueConstraint,
    # and payment_id's own UNIQUE for that matter).
    #
    # This has to be a PARTIAL unique index (only applies to non-terminal
    # statuses) rather than a plain UniqueConstraint on payment_id alone,
    # because a payment legitimately accumulates multiple recovery cases
    # over its history if it fails, recovers, and fails again -- what's
    # invalid is two OPEN/IN_PROGRESS cases open on the same payment at
    # once, not two cases ever.
    #
    # SQLite (used by the test suite) doesn't support partial indexes via
    # SQLAlchemy Core's postgresql_where in the same way in all versions,
    # but modern SQLite *does* support partial indexes with a plain WHERE
    # clause -- so this single index definition works on both backends
    # without a dialect branch.
    op.create_index(
        'uq_recovery_cases_one_open_per_payment',
        'recovery_cases',
        ['payment_id'],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('RECOVERED', 'EXHAUSTED', 'CANCELLED')"),
        sqlite_where=sa.text("status NOT IN ('RECOVERED', 'EXHAUSTED', 'CANCELLED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recovery_cases_one_open_per_payment', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_recovery_cases_status', table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_payment_id', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
