"""add failure_reason to payments

Revision ID: ce34b5219ac1
Revises: 95f7c2bb04cb
Create Date: 2026-08-27 04:49:37.254838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce34b5219ac1'
down_revision: Union[str, None] = '95f7c2bb04cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('failure_reason', sa.String(length=64), nullable=True))
    # NOTE: autogenerate also proposed dropping/recreating
    # uq_recovery_cases_one_open_per_payment here. That's a false
    # positive -- SQLAlchemy's autogenerate can't reliably introspect a
    # partial index's WHERE clause against a model that declares no such
    # index in Python (it was added by hand in the prior migration, see
    # 95f7c2bb04cb). This migration only adds the new column; the
    # partial index is untouched.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'failure_reason')
    # ### end Alembic commands ###
